# This file is automatically generated via the Auth0 CLI.
# It can be safely removed after the successful generation
# of Terraform resource definition files.

import {
  id = "2c7c33cd-06ea-498c-b4e6-2ff595f2a07c"
  to = auth0_attack_protection.attack_protection
}

import {
  id = "ef687241-1019-4bfa-8a5f-a4e8a887be99"
  to = auth0_branding.branding
}

import {
  id = "do8fXKTQxUudKsgJkPcRY3eHa7lPhwkf"
  to = auth0_client.default_app
}

import {
  id = "yaCluzV3X4Hpsme8wi2AXLQ9ExTtTpO1"
  to = auth0_client.aws_sso
}

import {
  id = "con_m652BJckuQB7BZ1M"
  to = auth0_connection.google_oauth2
}

import {
  id = "con_m652BJckuQB7BZ1M"
  to = auth0_connection_clients.google_oauth2
}

import {
  id = "con_0CRUvwwQY2sLc4wJ"
  to = auth0_connection.username_password_authentication
}

import {
  id = "con_0CRUvwwQY2sLc4wJ"
  to = auth0_connection_clients.username_password_authentication
}

import {
  id = "2ae4dcbe-2163-44ef-b833-e3b917c1bde1"
  to = auth0_guardian.guardian
}

import {
  id = "d67a2cc6-2ab6-4621-8a32-264b21c4f720"
  to = auth0_pages.pages
}

import {
  id = "b0c6eb9a-bbd2-4e20-aaf9-f1547cc5d1b4"
  to = auth0_prompt.prompts
}

import {
  id = "login::en"
  to = auth0_prompt_custom_text.en_login
}

import {
  id = "login-id::en"
  to = auth0_prompt_custom_text.en_login_id
}

import {
  id = "login-password::en"
  to = auth0_prompt_custom_text.en_login_password
}

import {
  id = "login-email-verification::en"
  to = auth0_prompt_custom_text.en_login_email_verification
}

import {
  id = "signup::en"
  to = auth0_prompt_custom_text.en_signup
}

import {
  id = "signup-id::en"
  to = auth0_prompt_custom_text.en_signup_id
}

import {
  id = "signup-password::en"
  to = auth0_prompt_custom_text.en_signup_password
}

import {
  id = "reset-password::en"
  to = auth0_prompt_custom_text.en_reset_password
}

import {
  id = "consent::en"
  to = auth0_prompt_custom_text.en_consent
}

import {
  id = "mfa-push::en"
  to = auth0_prompt_custom_text.en_mfa_push
}

import {
  id = "mfa-otp::en"
  to = auth0_prompt_custom_text.en_mfa_otp
}

import {
  id = "mfa-voice::en"
  to = auth0_prompt_custom_text.en_mfa_voice
}

import {
  id = "mfa-phone::en"
  to = auth0_prompt_custom_text.en_mfa_phone
}

import {
  id = "mfa-webauthn::en"
  to = auth0_prompt_custom_text.en_mfa_webauthn
}

import {
  id = "mfa-sms::en"
  to = auth0_prompt_custom_text.en_mfa_sms
}

import {
  id = "mfa-email::en"
  to = auth0_prompt_custom_text.en_mfa_email
}

import {
  id = "mfa-recovery-code::en"
  to = auth0_prompt_custom_text.en_mfa_recovery_code
}

import {
  id = "mfa::en"
  to = auth0_prompt_custom_text.en_mfa
}

import {
  id = "status::en"
  to = auth0_prompt_custom_text.en_status
}

import {
  id = "device-flow::en"
  to = auth0_prompt_custom_text.en_device_flow
}

import {
  id = "email-verification::en"
  to = auth0_prompt_custom_text.en_email_verification
}

import {
  id = "email-otp-challenge::en"
  to = auth0_prompt_custom_text.en_email_otp_challenge
}

import {
  id = "organizations::en"
  to = auth0_prompt_custom_text.en_organizations
}

import {
  id = "invitation::en"
  to = auth0_prompt_custom_text.en_invitation
}

import {
  id = "common::en"
  to = auth0_prompt_custom_text.en_common
}

import {
  id = "65219b388a2aad7b7fe9bd1f"
  to = auth0_resource_server.auth0_management_api
}

import {
  id = "d3505411-9f4e-47be-969c-9c18b5065f5f"
  to = auth0_tenant.tenant
}
