# This file is dynamically generated by Terraform. Do not edit manually.

[vpn_server]
${wg_server_ip} ansible_user=ubuntu ansible_ssh_private_key_file=${wg_ssh_private_key_path}

[n8n_server]
${n8n_server_ip} ansible_user=ubuntu ansible_ssh_private_key_file=${n8n_ssh_private_key_path} ansible_ssh_common_args='-o ProxyCommand="ssh -q ubuntu@${wg_server_ip} -i ${wg_ssh_private_key_path} -W %h:%p"'
